# Site settings
title: "徐云成-生态水动力学课题组 Eco-Hydrodynamics Group"
title1: "徐云成-生态水动力学课题组<br>Eco-Hydrodynamics Group"
email: ycxu@cau.edu.cn
description: 生态水动力学课题组（Eco-Hydro Group）是由中国农业大学徐云成负责，主要关注水利工程、农业工程、环境工程等研究领域中的生物（动物/植物）习性-水动力环境耦合相关的科学问题和工程问题，具体问题包括但不限于输调水工程生物污损、微灌系统灌水器堵塞、喷灌引起的冠层截留、灌溉影响下的作物生长模型等。
   我们主要使用理论建模和基于OpenFOAM的数值计算方法，辅以试验手段，与生态行为学、农业工程等方面的研究者合作，在复杂自然条件或人造工程中，探索动物、植物、微生物与水环境发生的物质交换、动量传递等过程，揭示其中的水动力学机理，对生物的生理结构奥秘和运动行为规律做出解释，为输调水系统、灌溉系统、河道生态修复等工程设计以及仿生机械设计提供理论依据和技术指导。
    The Eco-Hydrodynamics Group (Eco-Hydro Group) is led by Dr. Yuncheng Xu at China Agricultural University (CAU). We mainly focus on the scientific questions and engineering problems related to the coupling between biological (animal/plant)
    habits and the hydrodynamic environment, in the research fields of hydraulic engineering, agricultural engineering, environmental engineering, and so forth. The specific questions may include but not limit to bio-fouling in water-transfer
    projects, emitter clogging in micro-irrigation systems, canopy interception in spraying irrigation, plant growth modeling affected by irrigation, and so forth.
    We utilize theoretical modeling and numerical simulation based on OpenFOAM, supplemented by experimental methods, to explore the processes such as mass transfer and momentum transport between animals, plants, microorganisms and the
    aquatic environment, in the complex natural conditions and man-made structures, in the cooperation with researchers in ecological Behaviors and agricultural engineering. We want to explain the mysteries of biological structures and locomotion
    behaviors, by revealing the hydrodynamics mechanisms involved. Ultimately, our studies will provide theoretical and technical guides for the engineering designs such as water-transfer systems, irrigation systems, stream restoration, and bionic
    mechanical designs.
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
#google_analytics: UA-167467135-1
#google_analytics_4: G-02KDGRRB2T
#google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    <a href="http://water.cau.edu.cn/" target="_blank">水利与土木工程学院 <br/><span style="font-size: 0.8rem"> College of Water Resources and Civil Engineering</span></a>
    <br/><br/>
    <a href="http://www.cau.edu.cn/" target="_blank">中国农业大学 <br/>China Agricultural University</a>

location: >
  中以楼 A402 <br/>

contact: >
    <a href="mailto:ycxu@cau.edu.cn" target="_blank"><i class="fa fa-envelope fa-1x"></i> 通过邮件联系<br/>Contact via email</a>
    <br/><br/>
    <a href="https://faculty.cau.edu.cn/xyc/list.htm" target="_blank">学校个人网页 <br/><span style="font-size: 0.8rem">Personal Website at China Agricultural University</span></a>

# Pages shown in navbar
nav_pages:
  - name: 
      name1: members
      name2: 团队成员
  - name: 
      name1: projects
      name2: 项目介绍
  - name: 
      name1: publications
      name2: 学术论文
  - name: 
      name1: openings
      name2: 招生信息

  - name: 
      name1: courses
      name2: 课程信息      
#  - name: publications
#  - name: talks
#  - name: research
#  - name: software
# - name: teaching

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Xu
  first_name: [Yuncheng]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
